"""Tiny, safe markdown renderer for the digest subset.

The daily digest is machine-generated by the engine itself, so this only
needs to handle the markup build_digest emits: headings, ordered lists,
blockquotes, inline code/bold/italic, and links. Output is escaped and
links are restricted to http(s) so even a malformed digest can't inject.
"""

from __future__ import annotations

import html
import re

_LINK = re.compile(r"\[([^\]]+)\]\((https?://[^\s)]+)\)")
_BOLD = re.compile(r"\*\*([^*]+)\*\*")
_ITALIC = re.compile(r"\*([^*]+)\*")
_CODE = re.compile(r"`([^`]+)`")


def _escape(text: str) -> str:
    return html.escape(text, quote=True)


def _inline(text: str) -> str:
    text = _escape(text)
    text = _CODE.sub(r"<code>\1</code>", text)
    text = _BOLD.sub(r"<strong>\1</strong>", text)
    text = _ITALIC.sub(r"<em>\1</em>", text)
    text = _LINK.sub(r'<a href="\2" rel="noreferrer" target="_blank">\1</a>', text)
    return text


def render_digest(markdown: str) -> str:
    """Render the digest markdown to safe HTML."""
    out: list[str] = []
    in_ol = False
    in_ul = False

    def close_lists() -> None:
        nonlocal in_ol, in_ul
        if in_ol:
            out.append("</ol>")
            in_ol = False
        if in_ul:
            out.append("</ul>")
            in_ul = False

    for raw in markdown.splitlines():
        line = raw.rstrip()

        if not line.strip():
            close_lists()
            continue

        if line.startswith("# "):
            close_lists()
            out.append(f"<h1>{_inline(line[2:])}</h1>")
        elif line.startswith("## "):
            close_lists()
            out.append(f"<h2>{_inline(line[3:])}</h2>")
        elif line.startswith("### "):
            close_lists()
            out.append(f"<h3>{_inline(line[4:])}</h3>")
        elif line.startswith("> "):
            close_lists()
            out.append(f"<blockquote>{_inline(line[2:])}</blockquote>")
        elif re.match(r"^\d+\.\s", line):
            if in_ul:
                out.append("</ul>")
                in_ul = False
            if not in_ol:
                out.append("<ol>")
                in_ol = True
            body = re.sub(r"^\d+\.\s", "", line)
            out.append(f"<li>{_inline(body)}</li>")
        elif line.startswith("- "):
            if in_ol:
                out.append("</ol>")
                in_ol = False
            if not in_ul:
                out.append("<ul>")
                in_ul = True
            out.append(f"<li>{_inline(line[2:])}</li>")
        else:
            close_lists()
            out.append(f"<p>{_inline(line)}</p>")

    close_lists()
    return "\n".join(out)
